{
 "title": "Kaspr Scheduler",
 "description": "Monitor Kaspr Scheduler Applications",
 "tags": [
  "kaspr",
  "scheduler"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" },
   {
    "name": "kubernetes_namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(kaspr_app_info{kms_enabled=\"1\"})"
    }
   },
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "query_result(kaspr_app_info{kms_enabled=\"1\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "description": "Kaspr version",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kaspr_app_info{namespace=\"$kubernetes_namespace\", app_name=\"$app_name\"}) by (kaspr_version)",
     "legendFormat": "{{ kaspr_version }}"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "stat",
   "description": "Total number of partitions for timetable.",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kaspr_kms_last_location_time{namespace=\"$kubernetes_namespace\", app_name=\"$app_name\", type=\"D\"}) by (partition))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "stat",
   "description": "Total number of scheduler workers.",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kaspr_app_info{namespace=\"$kubernetes_namespace\", app_name=\"$app_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dispatchers",
   "type": "stat",
   "description": "Total number of active dispatchers.",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kaspr_kms_dispatcher_info{namespace=\"$kubernetes_namespace\", app_name=\"$app_name\", state=\"ACTIVE\"} > 0) by (app_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Janitors",
   "type": "stat",
   "description": "Total number of janitors.",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kaspr_kms_janitor_info{namespace=\"$kubernetes_namespace\", app_name=\"$app_name\", state=\"ACTIVE\"} > 0) by (app_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timetable Size",
   "type": "stat",
   "description": "Total number of keys contained in Timetable. (Note: this does not represent the actual number of scheduled messages.)",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kaspr_kms_timetable_size{namespace=\"$kubernetes_namespace\", app_name=\"$app_name\"}) by (app_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduled Last Hr",
   "type": "stat",
   "description": "Total number of deliveries since start.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kaspr_kms_messages_scheduled_total{namespace=\"$kubernetes_namespace\", app_name=\"$app_name\"}[1h])) by (namespace, app_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deliveried Last Hr",
   "type": "stat",
   "description": "Total number of deliveries since start.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kaspr_kms_messages_delivered_total{namespace=\"$kubernetes_namespace\", app_name=\"$app_name\"}[1h])) by (namespace, app_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deleted Last Hr",
   "type": "stat",
   "description": "Total number of messages removed from Timetable since start.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kaspr_kms_messages_removed_total{namespace=\"$kubernetes_namespace\", app_name=\"$app_name\"}[1h])) by (namespace, app_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Status",
   "type": "table",
   "description": "Worker information. All scheduling activities are distributed across one or more workers. Each worker is assigned timetable partitions to operate on.",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - max(max_over_time(kaspr_app_info{namespace=\"$kubernetes_namespace\", app_name=\"$app_name\"}[1m])) by (app_name, worker_name)"
    },
    {
     "expr": "max(kaspr_health{namespace=~\"$kubernetes_namespace\", app_name=\"$app_name\"}) by (app_name, worker_name)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Total application CPU utilization.",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(kaspr_cpu_utiliztion_percent{namespace=\"$kubernetes_namespace\", app_name=~\"$app_name\"}) by (namespace, app_name, worker_name)",
     "legendFormat": "{{  worker_name }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Worker memory usage.",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(max_over_time(kaspr_resident_memory_total{namespace=\"$kubernetes_namespace\", app_name=\"$app_name\"}[1m])) by (namespace, app_name, worker_name)",
     "legendFormat": "{{worker_name}}"
    }
   ]
  },
  {
   "title": "Disk Space Utilization",
   "type": "bargauge",
   "description": "Disk space utilization.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kaspr_disk_space_used{namespace=\"$kubernetes_namespace\",app_name=\"$app_name\"}) by (namespace, app_name, worker_name) / sum(kaspr_disk_space_total{namespace=\"$kubernetes_namespace\",app_name=\"$app_name\"}) by (namespace, app_name, worker_name)",
     "legendFormat": "{{worker_name}}"
    }
   ]
  },
  {
   "title": "Dispatchers",
   "type": "table",
   "description": "Dispatcher information. Dispatchers are responsible for delivering messages on time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(kaspr_kms_last_location_time{namespace=\"$kubernetes_namespace\", app_name=\"$app_name\", type=\"D\"}) by (app_name, worker_name, partition) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(kaspr_kms_last_location_lag{namespace=\"$kubernetes_namespace\", app_name=\"$app_name\", type=\"D\"}) by (app_name, worker_name, partition)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(kaspr_kms_last_location_seq{namespace=\"$kubernetes_namespace\", app_name=\"$app_name\", type=\"D\"}) by (app_name, worker_name, partition)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kaspr_kms_active_deliveries{namespace=\"$kubernetes_namespace\", app_name=\"$app_name\"}) by (namespace, worker_name, partition)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Janitors",
   "type": "table",
   "description": "Janitor  information. Janitors are responsible for removing delivered messages from the timetable.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(kaspr_kms_last_location_time{namespace=\"$kubernetes_namespace\", app_name=\"$app_name\", type=\"J\"}) by (app_name, worker_name, partition) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(kaspr_kms_last_location_lag{namespace=\"$kubernetes_namespace\", app_name=\"$app_name\", type=\"J\"}) by (app_name, worker_name, partition)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(kaspr_kms_last_location_seq{namespace=\"$kubernetes_namespace\", app_name=\"$app_name\", type=\"J\"}) by (app_name, worker_name, partition)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kaspr_kms_active_removals{namespace=\"$kubernetes_namespace\", app_name=\"$app_name\"}) by (namespace, worker_name, partition)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Schedule Rate",
   "type": "timeseries",
   "description": "Rate of messages scheduled",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kaspr_kms_messages_scheduled_total{app_name=\"$app_name\", namespace=\"$kubernetes_namespace\"}[1m])) by (namespace, app_name, worker_name)",
     "legendFormat": "{{ worker_name  }}"
    }
   ]
  },
  {
   "title": "Delivery Rate",
   "type": "timeseries",
   "description": "Rate of messages delivered",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kaspr_kms_messages_delivered_total{app_name=\"$app_name\", namespace=\"$kubernetes_namespace\"}[1m])) by (namespace, app_name, worker_name)",
     "legendFormat": "{{ worker_name  }}"
    }
   ]
  },
  {
   "title": "Instant Delivery Rate",
   "type": "timeseries",
   "description": "Rate of messages delivered instantly (without delay).",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kaspr_kms_messages_delivered_instant_total{app_name=\"$app_name\", namespace=\"$kubernetes_namespace\"}[1m])) by (namespace, app_name, worker_name)",
     "legendFormat": "{{ worker_name  }}"
    }
   ]
  },
  {
   "title": "Deletion Rate",
   "type": "timeseries",
   "description": "Rate of messages deleted from Timetable.",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kaspr_kms_messages_removed_total{app_name=\"$app_name\", namespace=\"$kubernetes_namespace\"}[1m])) by (namespace, app_name, worker_name)",
     "legendFormat": "{{ worker_name  }}"
    }
   ]
  },
  {
   "title": "Table Operations Rate",
   "type": "timeseries",
   "description": "Rate of operations on Scheduler's Timetable.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kaspr_table_operations_total{app_name=\"$app_name\", namespace=\"$kubernetes_namespace\"}[1m])) by (namespace, app_name, operation, table)",
     "legendFormat": "{{ operation }}: {{ table }}"
    }
   ]
  },
  {
   "title": "Consumer Rate",
   "type": "timeseries",
   "description": "Rate of events received per stream",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kaspr_messages_received_per_topic_total{namespace=\"$kubernetes_namespace\", app_name=\"$app_name\"}[1m])) by (namespace, app_name, topic)",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Producer Rate",
   "type": "timeseries",
   "description": "Rate of messages sent per topic",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kaspr_topic_messages_sent_total{namespace=\"$kubernetes_namespace\", app_name=\"$app_name\"}[1m])) by (namespace, app_name, topic)",
     "legendFormat": "{{ topic }}"
    },
    {
     "expr": "sum(rate(kaspr_total_error_messages_sent_total{namespace=\"$kubernetes_namespace\", app_name=\"$app_name\"}[1m])) by (namespace, app_name)",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Producer Send Duration",
   "type": "timeseries",
   "description": "Producer send latency in ms",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(histogram_quantile(0.50, sum(rate(kaspr_producer_send_latency_bucket{app_name=\"$app_name\", namespace=\"$kubernetes_namespace\"}[1m])) by (le)) / 1000)",
     "legendFormat": "P50"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(rate(kaspr_producer_send_latency_bucket{app_name=\"$app_name\", namespace=\"$kubernetes_namespace\"}[1m])) by (le)) / 1000)",
     "legendFormat": "P90"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(rate(kaspr_producer_send_latency_bucket{app_name=\"$app_name\", namespace=\"$kubernetes_namespace\"}[1m])) by (le)) / 1000)",
     "legendFormat": "P95"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(rate(kaspr_producer_send_latency_bucket{app_name=\"$app_name\", namespace=\"$kubernetes_namespace\"}[1m])) by (le)) / 1000) ",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Worker Rebalance Duration",
   "type": "timeseries",
   "description": "End to end rebalance latency.",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(histogram_quantile(0.50, sum(rate(kaspr_rebalance_done_latency_bucket{app_name=\"$app_name\", namespace=\"$kubernetes_namespace\"}[1m])) by (le)) / 1000)",
     "legendFormat": "P50"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(rate(kaspr_rebalance_done_latency_bucket{app_name=\"$app_name\", namespace=\"$kubernetes_namespace\"}[1m])) by (le)) / 1000)",
     "legendFormat": "P90"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(rate(kaspr_rebalance_done_latency_bucket{app_name=\"$app_name\", namespace=\"$kubernetes_namespace\"}[1m])) by (le)) / 1000)",
     "legendFormat": "P95"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(rate(kaspr_rebalance_done_latency_bucket{app_name=\"$app_name\", namespace=\"$kubernetes_namespace\"}[1m])) by (le)) / 1000) ",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Producer Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kaspr_total_error_messages_sent_total{namespace=\"$kubernetes_namespace\", app_name=\"$app_name\"}[1m])) by (namespace, app_name)",
     "legendFormat": "error"
    }
   ]
  }
 ]
}