apiVersion: kaspr.io/v1alpha1
kind: KasprApp
metadata:
  name: example-minimal-packages
  namespace: default
spec:
  replicas: 1
  bootstrapServers: "kafka:9092"
  
  # Minimal Python packages configuration
  # By default, uses ephemeral storage (emptyDir) - packages are reinstalled on each pod start
  # This works on any Kubernetes cluster without requiring special storage
  pythonPackages:
    packages:
      - requests
      - pandas
